// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab_2.DictionaryComponents;

#nullable disable

namespace lab_3.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20231229022754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("lab_2.DictionaryComponents.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("WordId");

                    b.ToTable("JsonDbSet");
                });

        }
    }
}
